# Generated by Django 5.0.2 on 2024-02-10 12:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_course_teacher_coursefeedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='blocked_students',
            field=models.ManyToManyField(related_name='blocked_courses', to=settings.AUTH_USER_MODEL),
        ),
    ]
