# Generated by Django 5.0.2 on 2024-02-14 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_course_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='picture',
            field=models.FileField(blank=True, null=True, upload_to='main/profile/pictures/'),
        ),
    ]
