# Generated by Django 5.0.2 on 2024-02-15 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_user_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='picture',
            field=models.FileField(default='test_none', upload_to='main/profile/pictures/'),
            preserve_default=False,
        ),
    ]
