# Generated by Django 5.0.2 on 2024-02-16 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_coursefeedback_title_alter_course_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursefeedback',
            name='title',
        ),
        migrations.AlterField(
            model_name='coursefeedback',
            name='comment',
            field=models.TextField(default='-', max_length=100),
            preserve_default=False,
        ),
    ]
