# Generated by Django 5.0.2 on 2024-02-16 22:11

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_remove_coursefeedback_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursefeedback',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
