# Generated by Django 5.0.2 on 2024-02-21 22:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_coursefeedback_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursefeedback',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to=settings.AUTH_USER_MODEL),
        ),
    ]
